ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/AMDphreak/orbris/graphs/contributors"><img src="https://img.shields.io/github/contributors/AMDphreak/orbris.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/AMDphreak/orbris/network/members"><img src="https://img.shields.io/github/forks/AMDphreak/orbris.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/AMDphreak/orbris/stargazers"><img src="https://img.shields.io/github/stars/AMDphreak/orbris.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/AMDphreak/orbris/issues"><img src="https://img.shields.io/github/issues/AMDphreak/orbris.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">Solstice (orbris)</h3>
<p align="center">
A widget-style sun-moon cycle tracker built with D and dlangui.<br />
<a href="https://github.com/AMDphreak/orbris/issues">Report Bug</a>
&middot;
<a href="https://github.com/AMDphreak/orbris/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/AMDphreak/orbris.svg?style=for-the-badge[Contributors,link=https://github.com/AMDphreak/orbris/graphs/contributors]
image:https://img.shields.io/github/forks/AMDphreak/orbris.svg?style=for-the-badge[Forks,link=https://github.com/AMDphreak/orbris/network/members]
image:https://img.shields.io/github/stars/AMDphreak/orbris.svg?style=for-the-badge[Stars,link=https://github.com/AMDphreak/orbris/stargazers]
image:https://img.shields.io/github/issues/AMDphreak/orbris.svg?style=for-the-badge[Issues,link=https://github.com/AMDphreak/orbris/issues]

= Solstice (orbris)

A widget-style sun-moon cycle tracker built with D and dlangui.

link:https://github.com/AMDphreak/orbris/issues[Report Bug] ·
link:https://github.com/AMDphreak/orbris/issues[Request Feature]
endif::[]


== About The Project

A widget-style sun-moon cycle tracker built with D and dlangui.

link:#readme-top[back to top]

== Features

* Resizable vector graphic of the sun-moon cycle.
* Temporal position indicator based on time and location.
* Hidden settings menu (top right toggle).
* Toggleable location display.

link:#readme-top[back to top]

== Installation

Depends on `dub` and `dlangui`.

link:#readme-top[back to top]

== Usage

[source,powershell]
----
dub run
----

link:#readme-top[back to top]

== Contact

Ryan Johnson — link:https://twitter.com/amdphreak[@amdphreak]

* Project: https://github.com/AMDphreak/orbris
* Site: https://ryanjohnson.dev

link:#readme-top[back to top]
